language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
  - pip install codecov
  - python setup.py develop

script:
  - make cov
  - python setup.py check -rms


after_success:

  - codecov

deploy:
  provider: pypi
  user: aio-libs-bot
  password:
    secure: "En+U4kq5LKMrOQ2g8qGBLRbTPEfgNsLIcAfs264LjAtSb9Rc8g62wJ3s2Vob5f8k848ZcBmBh+K5M75gNIYZtP2wU1p4sHvTnz5bxSkdgN9A7gdgS8UdxwbIO6dUBGz3YTlXNcbRmiSbA8CL7M8ULswVtqTwpr864q80TBlj49+HbfszI2wb9UOu7kGW9i1qFtCRSagqe6V1MWhRc0H5nD8WmwzmlxMtllJfubDA4EpqAwAPPwfxYP7QQgo8L3e5CBcbDmLwvvjXkxrOpp6yae2003AWJXFNcygcpo2mt1BRe8/bXtIxXLET0djP7sj+3yu5XTksAI2JTcGVW9PZUr+NmhTeKTrAFQ+7qW+QNWQRRYlS5SokhOEoTRPRsH2D9kYKFy0wteBNNe2TD4o09KsqQHwY+Lpr5nlJUkX5HXBrHoGSQW9lNaQEq7nutpEwiTBCAdINjmfjKMxHIXfy93XfjR2wwGIoUr94i+yWG/zIkCKwr31s5CvfRbHmntU/jFTk6cqSTfzphk+7XEMWQlw8tRh55b641IY4/PMXqSXx8oNpoK4/lvrKG0KP4wSBBLjIOVSq46VPij3YQjnN2EzqECKess2D6Wrec3JaPukLtjCnOymbMq72BstnRI41THrL6bNpyUc7OkXL9NwoU6TNSXdMZoVA2lu6nRE6F+w="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    all_branches: true
    python: 3.6
